"""``TypedDict`` definitions for every shape an fmpsdk method can return —
one per response *shape*, not per method, so two methods that return
identical data (e.g. ``search_symbol``/``search_name``) share a type,
while two methods that merely live in the same group but answer
different questions (e.g. ``profile`` vs. ``profile_cik``) get separate
types even when structurally similar.

Each method's return-type annotation names the ``TypedDict`` it returns
— that's the fastest way to see a response's exact fields without
making a live call. These are organized into one module per FMP data
category (mirroring ``endpoints/``); this ``__init__.py`` re-exports
every name, so ``from fmpsdk.types import X`` works regardless of which
submodule ``X`` actually lives in.
"""

from __future__ import annotations

from .bulk import (
    BalanceSheetStatementBulkResult,
    BalanceSheetStatementGrowthBulkResult,
    CashFlowStatementBulkResult,
    CashFlowStatementGrowthBulkResult,
    DcfBulkResult,
    EarningsSurprisesBulkResult,
    EodBulkResult,
    EtfHolderBulkResult,
    IncomeStatementBulkResult,
    IncomeStatementGrowthBulkResult,
    KeyMetricsTtmBulkResult,
    PeersBulkResult,
    PriceTargetSummaryBulkResult,
    RatingBulkResult,
    RatiosTtmBulkResult,
    ScoresBulkResult,
    UpgradesDowngradesConsensusBulkResult,
)
from .analyst import (
    AnalystEstimatesResult,
    RatingsSnapshotResult,
    RatingsHistoricalResult,
    PriceTargetSummaryResult,
    PriceTargetConsensusResult,
    GradesResult,
    GradesHistoricalResult,
    GradesConsensusResult,
)
from .calendar import (
    DividendResult,
    EarningsResult,
    IposCalendarResult,
    IposDisclosureResult,
    IposProspectusResult,
    SplitResult,
)
from .chart import (
    HistoricalChartResult,
    HistoricalPriceEodLightResult,
    HistoricalPriceEodFullResult,
    HistoricalPriceEodNonSplitAdjustedResult,
    HistoricalPriceEodDividendAdjustedResult,
)
from .commitment_of_traders import (
    CommitmentOfTradersReportResult,
    CommitmentOfTradersAnalysisResult,
    CommitmentOfTradersListResult,
)
from .commodity import CommoditiesListResult
from .company import (
    ProfileResult,
    CompanyNotesResult,
    StockPeersResult,
    DelistedCompanyResult,
    EmployeeCountResult,
    MarketCapResult,
    SharesFloatResult,
    SharesFloatAllResult,
    MergersAcquisitionsResult,
    KeyExecutiveResult,
    ExecutiveCompensationResult,
    ExecutiveCompensationBenchmarkResult,
)
from .congress import (
    CongressionalTradeResult,
    SenateProfileResult,
    SenatePositionResult,
    SenateNetWorthResult,
    SenateNetWorthAggregatedResult,
)
from .crypto import CryptocurrencyListResult
from .dcf import (
    DiscountedCashFlowResult,
    LeveredDiscountedCashFlowResult,
    CustomDiscountedCashFlowResult,
    CustomLeveredDiscountedCashFlowResult,
)
from .directory import (
    StockListResult,
    FinancialStatementSymbolListResult,
    CikListResult,
    SymbolChangeResult,
    EtfListResult,
    ActivelyTradingListResult,
    AvailableExchangeResult,
    AvailableSectorResult,
    AvailableIndustryResult,
    AvailableCountryResult,
)
from .earnings_transcript import (
    EarningCallTranscriptResult,
    EarningCallTranscriptDatesResult,
    EarningCallTranscriptLatestResult,
    EarningsTranscriptListResult,
)
from .economics import (
    TreasuryRatesResult,
    EconomicIndicatorsResult,
    EconomicCalendarResult,
    MarketRiskPremiumResult,
)
from .esg import (
    EsgDisclosuresResult,
    EsgRatingsResult,
    EsgBenchmarkResult,
)
from .forex import ForexListResult
from .fundraisers import (
    CrowdfundingOfferingResult,
    CrowdfundingOfferingSearchResult,
    FundraisingResult,
    FundraisingSearchResult,
)
from .funds import (
    EtfHoldingsResult,
    EtfInfoSectorExposure,
    EtfInfoResult,
    EtfCountryWeightingsResult,
    EtfAssetExposureResult,
    EtfSectorWeightingsResult,
    FundsDisclosureHoldersLatestResult,
    FundsDisclosureResult,
    FundsDisclosureHoldersSearchResult,
    FundsDisclosureDatesResult,
)
from .indexes import (
    IndexListResult,
    IndexConstituentResult,
    HistoricalIndexConstituentResult,
)
from .insider_trades import (
    InsiderTradingResult,
    InsiderTradingReportingNameResult,
    InsiderTradingTransactionTypeResult,
    InsiderTradingStatisticsResult,
    AcquisitionOfBeneficialOwnershipResult,
)
from .institutional_ownership import (
    InstitutionalOwnershipLatestResult,
    InstitutionalOwnershipExtractResult,
    InstitutionalOwnershipDatesResult,
    InstitutionalOwnershipExtractAnalyticsHolderResult,
    InstitutionalOwnershipHolderPerformanceSummaryResult,
    InstitutionalOwnershipHolderIndustryBreakdownResult,
    InstitutionalOwnershipSymbolPositionsSummaryResult,
    InstitutionalOwnershipIndustrySummaryResult,
)
from .market_hours import (
    ExchangeMarketHoursResult,
    HolidaysByExchangeResult,
)
from .market_performance import (
    MarketMoverResult,
    SectorPerformanceResult,
    IndustryPerformanceResult,
    SectorPeResult,
    IndustryPeResult,
)
from .news import (
    FmpArticlesResult,
    NewsArticleResult,
)
from .quote import (
    QuoteResult,
    QuoteShortResult,
    AftermarketTradeResult,
    AftermarketQuoteResult,
    StockPriceChangeResult,
)
from .search import (
    SearchSymbolResult,
    SearchCikResult,
    SearchCusipResult,
    SearchIsinResult,
    CompanyScreenerResult,
    SearchExchangeVariantsResult,
)
from .sec_filings import (
    SecFilingResult,
    SecFilingSearchResult,
    SecFilingsCompanySearchResult,
    SecProfileResult,
    StandardIndustrialClassificationResult,
    IndustryClassificationResult,
)
from .statements import (
    IncomeStatementResult,
    BalanceSheetStatementResult,
    BalanceSheetStatementTtmResult,
    CashFlowStatementResult,
    LatestFinancialStatementsResult,
    KeyMetricsResult,
    KeyMetricsTtmResult,
    RatiosResult,
    RatiosTtmResult,
    FinancialScoresResult,
    OwnerEarningsResult,
    EnterpriseValuesResult,
    IncomeStatementGrowthResult,
    BalanceSheetStatementGrowthResult,
    CashFlowStatementGrowthResult,
    FinancialGrowthResult,
    FinancialReportsDatesResult,
    FinancialReportsJsonResult,
    IncomeStatementAsReportedResult,
    BalanceSheetStatementAsReportedResult,
    CashFlowStatementAsReportedResult,
    FinancialStatementFullAsReportedResult,
    RevenueProductSegmentationResult,
    RevenueGeographicSegmentationResult,
)
from .tipranks import (
    TipranksAnalystActionBreakdown,
    TipranksAnalystDirectoryResult,
    TipranksAnalystSummaryResult,
    TipranksFirmSummaryResult,
    TipranksPointInTimeResult,
    TipranksRatingResult,
    TipranksRecommendationBreakdown,
    TipranksSymbolSummaryResult,
)
from .technical_indicators import (
    SmaResult,
    EmaResult,
    WmaResult,
    DemaResult,
    TemaResult,
    RsiResult,
    StandardDeviationResult,
    WilliamsResult,
    AdxResult,
)

__all__ = [
    "AcquisitionOfBeneficialOwnershipResult",
    "ActivelyTradingListResult",
    "AdxResult",
    "AftermarketQuoteResult",
    "AftermarketTradeResult",
    "AnalystEstimatesResult",
    "AvailableCountryResult",
    "AvailableExchangeResult",
    "AvailableIndustryResult",
    "AvailableSectorResult",
    "BalanceSheetStatementAsReportedResult",
    "BalanceSheetStatementBulkResult",
    "BalanceSheetStatementGrowthBulkResult",
    "BalanceSheetStatementGrowthResult",
    "BalanceSheetStatementResult",
    "BalanceSheetStatementTtmResult",
    "CashFlowStatementAsReportedResult",
    "CashFlowStatementBulkResult",
    "CashFlowStatementGrowthBulkResult",
    "CashFlowStatementGrowthResult",
    "CashFlowStatementResult",
    "CikListResult",
    "CommitmentOfTradersAnalysisResult",
    "CommitmentOfTradersListResult",
    "CommitmentOfTradersReportResult",
    "CommoditiesListResult",
    "CompanyNotesResult",
    "CompanyScreenerResult",
    "CongressionalTradeResult",
    "CrowdfundingOfferingResult",
    "CrowdfundingOfferingSearchResult",
    "CryptocurrencyListResult",
    "CustomDiscountedCashFlowResult",
    "CustomLeveredDiscountedCashFlowResult",
    "DcfBulkResult",
    "DelistedCompanyResult",
    "DemaResult",
    "DiscountedCashFlowResult",
    "DividendResult",
    "EarningCallTranscriptDatesResult",
    "EarningCallTranscriptLatestResult",
    "EarningCallTranscriptResult",
    "EarningsResult",
    "EarningsSurprisesBulkResult",
    "EarningsTranscriptListResult",
    "EconomicCalendarResult",
    "EconomicIndicatorsResult",
    "EmaResult",
    "EmployeeCountResult",
    "EnterpriseValuesResult",
    "EodBulkResult",
    "EsgBenchmarkResult",
    "EsgDisclosuresResult",
    "EsgRatingsResult",
    "EtfAssetExposureResult",
    "EtfCountryWeightingsResult",
    "EtfHolderBulkResult",
    "EtfHoldingsResult",
    "EtfInfoResult",
    "EtfInfoSectorExposure",
    "EtfListResult",
    "EtfSectorWeightingsResult",
    "ExchangeMarketHoursResult",
    "ExecutiveCompensationBenchmarkResult",
    "ExecutiveCompensationResult",
    "FinancialGrowthResult",
    "FinancialReportsDatesResult",
    "FinancialReportsJsonResult",
    "FinancialScoresResult",
    "FinancialStatementFullAsReportedResult",
    "FinancialStatementSymbolListResult",
    "FmpArticlesResult",
    "ForexListResult",
    "FundraisingResult",
    "FundraisingSearchResult",
    "FundsDisclosureDatesResult",
    "FundsDisclosureHoldersLatestResult",
    "FundsDisclosureHoldersSearchResult",
    "FundsDisclosureResult",
    "GradesConsensusResult",
    "GradesHistoricalResult",
    "GradesResult",
    "HistoricalChartResult",
    "HistoricalIndexConstituentResult",
    "HistoricalPriceEodDividendAdjustedResult",
    "HistoricalPriceEodFullResult",
    "HistoricalPriceEodLightResult",
    "HistoricalPriceEodNonSplitAdjustedResult",
    "HolidaysByExchangeResult",
    "IncomeStatementAsReportedResult",
    "IncomeStatementBulkResult",
    "IncomeStatementGrowthBulkResult",
    "IncomeStatementGrowthResult",
    "IncomeStatementResult",
    "IndexConstituentResult",
    "IndexListResult",
    "IndustryClassificationResult",
    "IndustryPeResult",
    "IndustryPerformanceResult",
    "InsiderTradingReportingNameResult",
    "InsiderTradingResult",
    "InsiderTradingStatisticsResult",
    "InsiderTradingTransactionTypeResult",
    "InstitutionalOwnershipDatesResult",
    "InstitutionalOwnershipExtractAnalyticsHolderResult",
    "InstitutionalOwnershipExtractResult",
    "InstitutionalOwnershipHolderIndustryBreakdownResult",
    "InstitutionalOwnershipHolderPerformanceSummaryResult",
    "InstitutionalOwnershipIndustrySummaryResult",
    "InstitutionalOwnershipLatestResult",
    "InstitutionalOwnershipSymbolPositionsSummaryResult",
    "IposCalendarResult",
    "IposDisclosureResult",
    "IposProspectusResult",
    "KeyExecutiveResult",
    "KeyMetricsResult",
    "KeyMetricsTtmBulkResult",
    "KeyMetricsTtmResult",
    "LatestFinancialStatementsResult",
    "LeveredDiscountedCashFlowResult",
    "MarketCapResult",
    "MarketMoverResult",
    "MarketRiskPremiumResult",
    "MergersAcquisitionsResult",
    "NewsArticleResult",
    "OwnerEarningsResult",
    "PeersBulkResult",
    "PriceTargetConsensusResult",
    "PriceTargetSummaryBulkResult",
    "PriceTargetSummaryResult",
    "ProfileResult",
    "QuoteResult",
    "QuoteShortResult",
    "RatingBulkResult",
    "RatingsHistoricalResult",
    "RatingsSnapshotResult",
    "RatiosResult",
    "RatiosTtmBulkResult",
    "RatiosTtmResult",
    "RevenueGeographicSegmentationResult",
    "RevenueProductSegmentationResult",
    "RsiResult",
    "ScoresBulkResult",
    "SearchCikResult",
    "SearchCusipResult",
    "SearchExchangeVariantsResult",
    "SearchIsinResult",
    "SearchSymbolResult",
    "SecFilingResult",
    "SecFilingSearchResult",
    "SecFilingsCompanySearchResult",
    "SecProfileResult",
    "SectorPeResult",
    "SectorPerformanceResult",
    "SenateNetWorthAggregatedResult",
    "SenateNetWorthResult",
    "SenatePositionResult",
    "SenateProfileResult",
    "SharesFloatAllResult",
    "SharesFloatResult",
    "SmaResult",
    "SplitResult",
    "StandardDeviationResult",
    "StandardIndustrialClassificationResult",
    "StockListResult",
    "StockPeersResult",
    "StockPriceChangeResult",
    "SymbolChangeResult",
    "TemaResult",
    "TipranksAnalystActionBreakdown",
    "TipranksAnalystDirectoryResult",
    "TipranksAnalystSummaryResult",
    "TipranksFirmSummaryResult",
    "TipranksPointInTimeResult",
    "TipranksRatingResult",
    "TipranksRecommendationBreakdown",
    "TipranksSymbolSummaryResult",
    "TreasuryRatesResult",
    "UpgradesDowngradesConsensusBulkResult",
    "WilliamsResult",
    "WmaResult",
]
