#!/usr/bin/env python3
"""Generate ``openapi.json`` at the repo root by introspecting ``fmpsdk``.

    python tools/gen_openapi.py            # writes ./openapi.json
    python tools/gen_openapi.py --check    # exit 1 if the file is stale

IMPORTANT: the output is *generated from the fmpsdk source*, not fetched from
Financial Modeling Prep. FMP publishes no OpenAPI/Swagger document. The
disclaimer to that effect is written into ``info.description`` so it travels
with the file. See ``mcp/fmpsdk_mcp/catalog.py`` for the shared introspection.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import typing
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "mcp"))

import fmpsdk  # noqa: E402
from fmpsdk import types as fmp_types  # noqa: E402
from fmpsdk.client import BASE_URL  # noqa: E402
from fmpsdk_mcp import catalog  # noqa: E402

OUT = REPO / "openapi.json"

DISCLAIMER = (
    "GENERATED — NOT AN OFFICIAL FINANCIAL MODELING PREP ARTIFACT. Financial "
    "Modeling Prep does not publish an OpenAPI/Swagger specification. This "
    f"document is produced by introspecting the fmpsdk Python library "
    f"(v{catalog.FMPSDK_VERSION}) — its method signatures, docstrings, and "
    "TypedDict response models — and is only as accurate as that library. It "
    "is not fetched from, generated by, or endorsed by Financial Modeling "
    "Prep. Regenerate with `python tools/gen_openapi.py`."
)

_SCALARS = {
    "str": {"type": "string"},
    "int": {"type": "integer"},
    "float": {"type": "number"},
    "bool": {"type": "boolean"},
    "bytes": {"type": "string", "format": "binary"},
    "Any": {},
    "None": {"type": "null"},
}

_schemas: dict[str, Any] = {}


def _anno_to_schema(text: str) -> dict[str, Any]:
    """Map a stringified annotation (``"int | None"``, ``"str"``) to a schema
    for a *parameter*. Good enough for query params, which are all scalar."""
    parts = [p.strip() for p in text.split("|")] if text else []
    non_null = [p for p in parts if p != "None"]
    base = (
        _SCALARS.get(non_null[0], {"type": "string"})
        if non_null
        else {"type": "string"}
    )
    if "None" in parts:
        base = {**base, "nullable": True}
    return base


def _typeddict_schema(td: type) -> dict[str, Any]:
    """Convert a TypedDict class to a JSON Schema object, registering it (and
    any nested TypedDicts) under ``components.schemas``."""
    name = td.__name__
    if name in _schemas:
        return {"$ref": f"#/components/schemas/{name}"}
    _schemas[name] = {}  # reserve the slot to break recursion

    props: dict[str, Any] = {}
    hints = typing.get_type_hints(td)
    for field, hint in hints.items():
        props[field] = _hint_schema(hint)

    schema = {
        "type": "object",
        "properties": props,
        "additionalProperties": False,
    }
    if td.__doc__:
        schema["description"] = " ".join(td.__doc__.split())
    _schemas[name] = schema
    return {"$ref": f"#/components/schemas/{name}"}


def _hint_schema(hint: Any) -> dict[str, Any]:
    """Convert a resolved typing object to JSON Schema (recursive)."""
    origin = typing.get_origin(hint)
    args = typing.get_args(hint)

    if origin is None:
        if hint in (str, int, float, bool, bytes):
            return dict(_SCALARS[hint.__name__])
        if hint is type(None):
            return {"type": "null"}
        if (
            isinstance(hint, type)
            and hasattr(hint, "__annotations__")
            and issubclass_typeddict(hint)
        ):
            return _typeddict_schema(hint)
        if hint is typing.Any:
            return {}
        return {}

    if origin is typing.Union or origin is getattr(
        __import__("types"), "UnionType", ()
    ):
        non_null = [a for a in args if a is not type(None)]
        sub = (
            _hint_schema(non_null[0])
            if len(non_null) == 1
            else {"anyOf": [_hint_schema(a) for a in non_null]}
        )
        if type(None) in args:
            sub = {**sub, "nullable": True}
        return sub

    if origin in (list, set, tuple):
        return {"type": "array", "items": _hint_schema(args[0]) if args else {}}

    if origin is dict:
        value = _hint_schema(args[1]) if len(args) == 2 else {}
        return {"type": "object", "additionalProperties": value}

    return {}


def issubclass_typeddict(cls: type) -> bool:
    return hasattr(cls, "__required_keys__") or hasattr(cls, "__optional_keys__")


def _return_schema(return_type: str) -> dict[str, Any]:
    """Schema for a method's return annotation string, e.g.
    ``"list[IncomeStatementResult]"``."""
    names = re.findall(r"\w+", return_type)
    if not names:
        return {}
    inner = names[-1]
    is_list = names[0] in ("list", "tuple", "set")
    td = getattr(fmp_types, inner, None)
    if td is not None and issubclass_typeddict(td):
        item = _typeddict_schema(td)
    elif inner == "dict":
        item = {"type": "object", "additionalProperties": {"type": "string"}}
    elif inner in _SCALARS:
        item = dict(_SCALARS[inner])
    else:
        item = {}
    return {"type": "array", "items": item} if is_list else item


def _param_docs(doc: str) -> dict[str, str]:
    """Pull ``:param name: text`` lines from a docstring, stripped of RST."""
    out: dict[str, str] = {}
    for name, text in re.findall(
        r":param (\w+):\s*(.+?)(?=\n\s*:param |\n\s*$|\Z)", doc, re.DOTALL
    ):
        clean = re.sub(r"``([^`]*)``", r"\1", " ".join(text.split()))
        out[name] = clean
    return out


def build_spec() -> dict[str, Any]:
    paths: dict[str, Any] = {}
    for e in catalog.build_catalog():
        if not e.wire_path:
            continue
        pdocs = _param_docs(e.doc)
        parameters = [
            {
                "name": p.name.rstrip("_"),  # from_ -> from, to stays to
                "in": "query",
                "required": p.required,
                "schema": _anno_to_schema(p.annotation),
                **({"description": pdocs[p.name]} if p.name in pdocs else {}),
            }
            for p in e.params
        ]
        operation = {
            "operationId": e.name,
            "summary": e.summary,
            "description": e.doc,
            "tags": [e.group],
            "parameters": parameters,
            "responses": {
                "200": {
                    "description": "Success",
                    "content": {
                        "application/json": {"schema": _return_schema(e.return_type)}
                    },
                }
            },
        }
        if e.tier:
            operation["x-fmp-plan-tier"] = e.tier
        paths.setdefault(f"/{e.wire_path}", {})[e.http_method.lower()] = operation

    return {
        "openapi": "3.1.0",
        "x-generated-by": "fmpsdk source introspection (tools/gen_openapi.py)",
        "x-not-official": True,
        "info": {
            "title": "Financial Modeling Prep API — as described by fmpsdk",
            "version": str(catalog.FMPSDK_VERSION),
            "description": DISCLAIMER,
            "license": {"name": "BSD-3-Clause"},
        },
        "servers": [{"url": BASE_URL.rstrip("/")}],
        "security": [{"apikey": []}],
        "tags": sorted(
            ({"name": g} for g in {e.group for e in catalog.build_catalog()}),
            key=lambda t: t["name"],
        ),
        "paths": dict(sorted(paths.items())),
        "components": {
            "securitySchemes": {
                "apikey": {"type": "apiKey", "in": "query", "name": "apikey"}
            },
            "schemas": dict(sorted(_schemas.items())),
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check", action="store_true", help="exit 1 if openapi.json is stale"
    )
    args = ap.parse_args()

    spec = build_spec()
    rendered = json.dumps(spec, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            print(
                "openapi.json is stale — run: python tools/gen_openapi.py",
                file=sys.stderr,
            )
            return 1
        print("openapi.json is up to date.")
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    ops = sum(len(v) for v in spec["paths"].values())
    print(
        f"wrote {OUT.relative_to(REPO)} — {ops} operations, {len(spec['components']['schemas'])} schemas"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
